/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Principal;

import Clases.Conexion;
import Clases.ContadorEstudiante;
import Clases.RegistroEstudiante;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Reymundo Tenorio
 */
public class ComedorP extends javax.swing.JFrame {

    /**
     * Creates new form Estudiante
     */
    public ComedorP() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        TabbedPane = new org.edisoncor.gui.tabbedPane.TabbedPaneHeader();
        PanelNuevo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtScan = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblCarnet = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblapellido = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblFacultad = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblCarrera = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblInasistencias = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLblFoto = new javax.swing.JLabel();
        lblRegistro = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnbuscar = new javax.swing.JButton();
        btnscan = new javax.swing.JButton();
        txtBuscar = new javax.swing.JFormattedTextField();
        btnok = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Comedor");
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        TabbedPane.setBackground(new java.awt.Color(0, 204, 204));
        TabbedPane.setColorDeBorde(new java.awt.Color(0, 204, 204));
        TabbedPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TabbedPaneMousePressed(evt);
            }
        });
        TabbedPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                TabbedPaneStateChanged(evt);
            }
        });

        PanelNuevo.setBackground(new java.awt.Color(0, 153, 204));
        PanelNuevo.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        txtScan.setPreferredSize(new java.awt.Dimension(0, 0));
        txtScan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtScanActionPerformed(evt);
            }
        });
        jPanel1.add(txtScan);

        PanelNuevo.add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel6.setBackground(new java.awt.Color(0, 153, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información Nuevo Estudiante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(204, 204, 204))); // NOI18N

        jPanel3.setBackground(new java.awt.Color(235, 235, 150));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridLayout(7, 2, 0, 5));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("No. Carné");
        jPanel3.add(jLabel5);

        lblCarnet.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        lblCarnet.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(lblCarnet);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombres");
        jPanel3.add(jLabel2);

        lblNombre.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(lblNombre);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Apellidos");
        jPanel3.add(jLabel4);

        lblapellido.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        lblapellido.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(lblapellido);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Sexo");
        jPanel3.add(jLabel6);

        lblSexo.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        lblSexo.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(lblSexo);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Facultad");
        jPanel3.add(jLabel8);

        lblFacultad.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        lblFacultad.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(lblFacultad);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Carrera");
        jPanel3.add(jLabel3);

        lblCarrera.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        lblCarrera.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(lblCarrera);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("No. Inasistencia En La Semana");
        jPanel3.add(jLabel7);

        lblInasistencias.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        lblInasistencias.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(lblInasistencias);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fotografía Estudiante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel9.setOpaque(false);

        jLblFoto.setForeground(new java.awt.Color(235, 235, 150));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLblFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblRegistro.setBackground(new java.awt.Color(255, 255, 255));
        lblRegistro.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblRegistro.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        PanelNuevo.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel4.setBackground(new java.awt.Color(235, 235, 150));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Estudiante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel4.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Buscar Por No. Carné: ");

        btnbuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnbuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar_1.png"))); // NOI18N
        btnbuscar.setMnemonic('b');
        btnbuscar.setText("Buscar");
        btnbuscar.setToolTipText("Buscar Agente Vendedor");
        btnbuscar.setContentAreaFilled(false);
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        btnscan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnscan.setForeground(new java.awt.Color(255, 255, 255));
        btnscan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Scan.png"))); // NOI18N
        btnscan.setMnemonic('e');
        btnscan.setText("Activar Escáner");
        btnscan.setToolTipText("Activar Escáner de Códigos de Barra");
        btnscan.setContentAreaFilled(false);
        btnscan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnscanActionPerformed(evt);
            }
        });

        try {
            txtBuscar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtBuscar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarKeyTyped(evt);
            }
        });

        btnok.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnok.setForeground(new java.awt.Color(255, 255, 255));
        btnok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/OK.png"))); // NOI18N
        btnok.setMnemonic('b');
        btnok.setText("Aceptar");
        btnok.setToolTipText("Buscar Agente Vendedor");
        btnok.setContentAreaFilled(false);
        btnok.setEnabled(false);
        btnok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnokActionPerformed(evt);
            }
        });

        btnCerrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cerrar.png"))); // NOI18N
        btnCerrar.setMnemonic('s');
        btnCerrar.setText("Cerrar Sesión");
        btnCerrar.setToolTipText("Cerrar El Registro de Estudiantes");
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnok, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144)
                .addComponent(btnscan, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnbuscar)
                            .addComponent(btnscan)
                            .addComponent(btnok)
                            .addComponent(btnCerrar))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtBuscar))
                .addContainerGap())
        );

        PanelNuevo.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        TabbedPane.addTab("Estudiantes", PanelNuevo);

        getContentPane().add(TabbedPane, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1209, 686));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
   
    private MenuPrincipal MP;

    public void setMP(MenuPrincipal MP) {
        this.MP = MP;
    }
    
    
    public static ResultSet resultado;


    
   
    
    public void CleanAll(){
        lblapellido.setText("");
        lblCarnet.setText("");
        lblNombre.setText("");
        lblCarnet.setText("");
        lblCarrera.setText("");
        lblFacultad.setText("");
        lblSexo.setText("");
        jLblFoto.setIcon(null);
    }
    
  
  
    
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
txtScan.requestFocus();
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
    MP.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void TabbedPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_TabbedPaneStateChanged

        // TODO add your handling code here:
    }//GEN-LAST:event_TabbedPaneStateChanged

    private void TabbedPaneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabbedPaneMousePressed

        // TODO add your handling code here:
    }//GEN-LAST:event_TabbedPaneMousePressed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
Buscar();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbuscarActionPerformed

   private int ID_Beca; 

    public void Buscar(){
        
        String Buscar = txtBuscar.getText();
   
        int ID = 0, Inasistencias = 0;
        String Nombres = "", Apellidos = "", NoCarnet = "", Sexo = "", 
                Facultad = "", Carrera = "", Activo = "";
        
        int ID_Estudiante = 0;
        
        
            try{
        resultado = Conexion.consulta("Select [ID_Estudiante] from [dbo].[Estudiante] where [No_Carne_Estudiante] = '"+Buscar+"'");
         
        while(resultado.next()){
            ID_Estudiante = resultado.getInt(1);
        }
         }catch(SQLException ex){
            JOptionPane.showMessageDialog(this, "Estudiante No Encontrado", "No Encontrado", JOptionPane.ERROR_MESSAGE);
            return;
         }
        
            if(ID_Estudiante == 0){
                JOptionPane.showMessageDialog(this, "Estudiante No Registrado En La Base de Datos"
                        , "No Registrado", JOptionPane.ERROR_MESSAGE);
            return;
            }
        
        try{
            
        
        resultado = Conexion.consulta("Select * from [dbo].[BecaAlimenticiaV] where [No_Carne_Estudiante] = '"+Buscar+"'");
        
        while(resultado.next()){
            
            ID = resultado.getInt(1);
            Nombres = resultado.getString(2);
            Apellidos = resultado.getString(3);
            NoCarnet = resultado.getString(4);
            Sexo = resultado.getString(5);
            Facultad = resultado.getString(6);
            Carrera = resultado.getString(7);
            Activo = resultado.getString(8);
            Inasistencias = resultado.getInt(9);
        }
        
        
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(this, "Estudiante No Encontrado", "No Encontrado", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
     
        lblNombre.setText(Nombres);
        lblapellido.setText(Apellidos);
        lblCarnet.setText(NoCarnet);
        lblSexo.setText(Sexo);
        lblFacultad.setText(Facultad);
        lblCarrera.setText(Carrera);
        
       
            byte[] fileBytes;
         String query;
                 
         try
                 {
                         query = "Select [Foto_Estudiante] from [dbo].[Estudiante] where [No_Carne_Estudiante] = '"+NoCarnet+"'";
                         Statement state = Conexion.con.createStatement();
                         ResultSet rs = state.executeQuery(query);
                         if (rs.next())
                        {
                                 fileBytes = rs.getBytes(1);
                                 ImageIcon n = null;
                                 try{
                                  n = new ImageIcon(fileBytes);
                               
                                 Image img = n.getImage();
                                 
                                 
                    Image newimg = img.getScaledInstance(458,429,java.awt.Image.SCALE_SMOOTH);
                    ImageIcon newIcon = new ImageIcon(newimg);
                    jLblFoto.setIcon(newIcon);
                    
                      }catch(NullPointerException ex){
                               
                                 }
                                 
                        }        
                        
                 }
                 catch (SQLException e)
                 {
                         JOptionPane.showMessageDialog(null, "Error Al Mostrar Imagen","Error",JOptionPane.ERROR_MESSAGE);
                        
                 }
         
        
           
        if("Activo".equals(Activo)){
        lblInasistencias.setText(String.valueOf(Inasistencias));
        PanelNuevo.setBackground(new java.awt.Color(0,153,204));
        jPanel6.setBackground(new java.awt.Color(0,153,204));
        jPanel1.setBackground(new java.awt.Color(0,102,153));
        btnok.setEnabled(true);
        this.ID_Beca = ID;
        
        }
        if("Inactivo".equals(Activo)){
               lblInasistencias.setText(String.valueOf(Inasistencias));
               PanelNuevo.setBackground(new java.awt.Color(255,0,0));
               jPanel6.setBackground(new java.awt.Color(255,0,0));
               jPanel1.setBackground(new java.awt.Color(153,0,0));
               lblRegistro.setText("BECA ALIMENTICIA DESACTIVADA");
               lblRegistro.setForeground(new java.awt.Color(255,153,0));
               btnok.setEnabled(false);
               
               txtScan.setText("");
               txtBuscar.setText("");
               btnok.requestFocus();
        }
        
          
        
    }
    
    
    public void BuscarScan() throws ParseException{
        
        String Buscar = txtScan.getText();
        int ID = 0, Inasistencias = 0;
        String Nombres = "", Apellidos = "", NoCarnet = "", Sexo = "", 
                Facultad = "", Carrera = "", Activo = "";
        
        int ID_Estudiante = 0;
        
        
            try{
        resultado = Conexion.consulta("Select [ID_Estudiante] from [dbo].[Estudiante] where [No_Carne_Estudiante] = '"+Buscar+"'");
         
        while(resultado.next()){
            ID_Estudiante = resultado.getInt(1);
        }
         }catch(SQLException ex){
            JOptionPane.showMessageDialog(this, "Estudiante No Encontrado", "No Encontrado", JOptionPane.ERROR_MESSAGE);
            return;
         }
        
            if(ID_Estudiante == 0){
                JOptionPane.showMessageDialog(this, "Estudiante No Registrado En La Base de Datos"
                        , "No Registrado", JOptionPane.ERROR_MESSAGE);
            return;
            }
        
        try{
            
        
        resultado = Conexion.consulta("Select * from [dbo].[BecaAlimenticiaV] where [No_Carne_Estudiante] = '"+Buscar+"'");
        
        while(resultado.next()){
            
            ID = resultado.getInt(1);
            Nombres = resultado.getString(2);
            Apellidos = resultado.getString(3);
            NoCarnet = resultado.getString(4);
            Sexo = resultado.getString(5);
            Facultad = resultado.getString(6);
            Carrera = resultado.getString(7);
            Activo = resultado.getString(8);
            Inasistencias = resultado.getInt(9);
        }
        
        
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(this, "Estudiante No Encontrado", "No Encontrado", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
     
        lblNombre.setText(Nombres);
        lblapellido.setText(Apellidos);
        lblCarnet.setText(NoCarnet);
        lblSexo.setText(Sexo);
        lblFacultad.setText(Facultad);
        lblCarrera.setText(Carrera);
        
       
            byte[] fileBytes;
         String query;
                 
         try
                 {
                         query = "Select [Foto_Estudiante] from [dbo].[Estudiante] where [No_Carne_Estudiante] = '"+NoCarnet+"'";
                         Statement state = Conexion.con.createStatement();
                         ResultSet rs = state.executeQuery(query);
                         if (rs.next())
                        {
                                 fileBytes = rs.getBytes(1);
                                 ImageIcon n = null;
                                 try{
                                  n = new ImageIcon(fileBytes);
                               
                                 Image img = n.getImage();
                                 
                                 
                    Image newimg = img.getScaledInstance(458,429,java.awt.Image.SCALE_SMOOTH);
                    ImageIcon newIcon = new ImageIcon(newimg);
                    jLblFoto.setIcon(newIcon);
                    
                      }catch(NullPointerException ex){
                               
                                 }
                                 
                        }        
                        
                 }
                 catch (SQLException e)
                 {
                         JOptionPane.showMessageDialog(null, "Error Al Mostrar Imagen","Error",JOptionPane.ERROR_MESSAGE);
                        
                 }
           
        if("Activo".equals(Activo)){
        lblInasistencias.setText(String.valueOf(Inasistencias));
        PanelNuevo.setBackground(new java.awt.Color(0,153,204));
        jPanel6.setBackground(new java.awt.Color(0,153,204));
        jPanel1.setBackground(new java.awt.Color(0,102,153));
 
        int Registrado = 0;  
        
        String dia, mes, ano;

        Calendar c = new GregorianCalendar();

        dia = Integer.toString(c.get(Calendar.DATE));
        mes = Integer.toString(c.get(Calendar.MONTH)+1);
        ano = Integer.toString(c.get(Calendar.YEAR));

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String strFecha =ano+"-"+mes+"-"+dia ;
        Date Fecha = sdf.parse(strFecha);
        String FechaF = sdf.format(Fecha);
        
        try{
        
      resultado = Conexion.consulta("Select [ID_BecaAlimenticia] from [dbo].[RegistroComedorE] "
              + "where ([ID_BecaAlimenticia] ="+ID+") and ([FechaContador] = '"+FechaF+"')");

            while (resultado.next()) {
               
                Registrado = 1;
                
            }
        }catch(SQLException ex){
            
        }
           
        String Hora = "";
        
        try{
        
      resultado = Conexion.consulta("SELECT Right( Convert(Datetime, [FechaHoraComedor], "
              + "108),8) as Fecha From [dbo].[RegistroComedorE] where "
              + "[ID_BecaAlimenticia] ="+ID);

            while (resultado.next()) {
               
                Hora = resultado.getString(1);
                
            }
        }catch(SQLException ex){
            
        }
      
        
if(Registrado == 1){
  JOptionPane.showMessageDialog(this, "Estudiante Ya Se Registró el Día de Hoy a Las "+Hora.trim(), "Ya Registrado",JOptionPane.ERROR_MESSAGE);
return;
}


    
        
        RegistroEstudiante.Agregar_RegistroEstudiante(ID_Estudiante, MenuPrincipal.ID_Usuario, "RUPAP");
        
        lblRegistro.setText("ESTUDIANTE REGISTRADO");
        lblRegistro.setForeground(new java.awt.Color(0,102,0));
        
        }
        if("Inactivo".equals(Activo)){
               lblInasistencias.setText(String.valueOf(Inasistencias));
               PanelNuevo.setBackground(new java.awt.Color(255,0,0));
               jPanel6.setBackground(new java.awt.Color(255,0,0));
               jPanel1.setBackground(new java.awt.Color(153,0,0));
               lblRegistro.setText("BECA ALIMENTICIA DESACTIVADA");
               lblRegistro.setForeground(new java.awt.Color(255,153,0));
        }
        
        txtScan.setText("");
        txtBuscar.setText("");
        txtScan.requestFocus();
    }
    
    private void btnscanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnscanActionPerformed
txtScan.requestFocus();
//txtBuscar.requestFocus();

// TODO add your handling code here:
    }//GEN-LAST:event_btnscanActionPerformed

    public void Aceptar() throws ParseException{
    
        
        String NoCarnet = lblCarnet.getText().trim();
        int ID = 0;
        
        
        try{
                   
        resultado = Conexion.consulta("Select [ID_Estudiante] from [dbo].[Estudiante] where [No_Carne_Estudiante] = '"+NoCarnet+"'");
        
        while(resultado.next()){
            
            ID = resultado.getInt(1);
        }
        
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(this, "Estudiante No Encontrado");
            return;
        }
        
          int Registrado = 0;  
        
        String dia, mes, ano;

        Calendar c = new GregorianCalendar();

        dia = Integer.toString(c.get(Calendar.DATE));
        mes = Integer.toString(c.get(Calendar.MONTH)+1);
        ano = Integer.toString(c.get(Calendar.YEAR));

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String strFecha =ano+"-"+mes+"-"+dia ;
        Date Fecha = sdf.parse(strFecha);
        String FechaF = sdf.format(Fecha);
        
        try{
        
      resultado = Conexion.consulta("Select [ID_BecaAlimenticia] from [dbo].[RegistroComedorE] "
              + "where ([ID_BecaAlimenticia] ="+this.ID_Beca+") and ([FechaContador] = '"+FechaF+"')");

            while (resultado.next()) {
               
                Registrado = 1;
                
            }
        }catch(SQLException ex){
            
        }
           
        String Hora = "";
        
        try{
        
      resultado = Conexion.consulta("SELECT Right( Convert(Datetime, [FechaHoraComedor], "
              + "108),8) as Fecha From [dbo].[RegistroComedorE] where "
              + "[ID_BecaAlimenticia] ="+this.ID_Beca);

            while (resultado.next()) {
               
                Hora = resultado.getString(1);
                
            }
        }catch(SQLException ex){
            
        }
      
        
if(Registrado == 1){
  JOptionPane.showMessageDialog(this, "Estudiante Ya Se Registró el Día de Hoy a Las "+Hora.trim(), "Ya Registrado",JOptionPane.ERROR_MESSAGE);
return;
}

this.ID_Beca = 0;

        
        RegistroEstudiante.Agregar_RegistroEstudiante(ID, MenuPrincipal.ID_Usuario, "RUPAP");       
        lblRegistro.setText("ESTUDIANTE REGISTRADO");
        lblRegistro.setForeground(new java.awt.Color(0,102,0));
        
        btnok.setEnabled(false);
        txtScan.setText("");
        txtBuscar.setText("");
        txtScan.requestFocus();
       
       
}
    
    private void txtScanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtScanActionPerformed

        
        try {
            BuscarScan();
        }catch(ParseException ex){
        }
              
            // TODO add your handling code here:
    }//GEN-LAST:event_txtScanActionPerformed

    private void txtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyTyped
if(evt.getKeyChar() == KeyEvent.VK_ENTER){

    Buscar();

}
// TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarKeyTyped

    private void btnokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnokActionPerformed

        try{
        Aceptar();   
        }catch(ParseException ex){
        }
        

// TODO add your handling code here:
    }//GEN-LAST:event_btnokActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
ContadorEstudiante.Agregar_ContadorEstudiante();        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed

        
        
        try {
            BuscarScan();
        }catch(ParseException ex){
            
        }
            
            
// TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComedorP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ComedorP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelNuevo;
    private org.edisoncor.gui.tabbedPane.TabbedPaneHeader TabbedPane;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btnok;
    private javax.swing.JButton btnscan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLblFoto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblCarnet;
    private javax.swing.JLabel lblCarrera;
    private javax.swing.JLabel lblFacultad;
    private javax.swing.JLabel lblInasistencias;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRegistro;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblapellido;
    private javax.swing.JFormattedTextField txtBuscar;
    private javax.swing.JTextField txtScan;
    // End of variables declaration//GEN-END:variables
}
