package WebCam;


import Principal.EstudianteP;
import Principal.TrabajadorP;
import java.awt.Frame;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Reymundo Tenorio
 */
public class ViewImageFrame extends javax.swing.JDialog {
private File Img=null;
private ImageIcon II=null;
private ImageIcon Imag=null;
private final String Ruta;
    /**
     * Creates new form ViewImageFrame
     * @param parent
     * @param modal
     * @param imagefile
     */
    public ViewImageFrame(Frame parent,boolean modal,String imagefile) {
        super(parent,modal);
        initComponents();
        this.Ruta = imagefile;
        Img=new File(imagefile);
        setTitle("Imágen: "+Img.getName()+" - WebCam Capture Viewer");
        II=new ImageIcon(Img.getAbsolutePath());
        Imag = new ImageIcon(II.getImage().
                                      getScaledInstance(640,480,
                                                        Image.SCALE_DEFAULT));
        Imagen.setIcon(Imag);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Imagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ver Imágen");
        setResizable(false);

        Imagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Imagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ImagenMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Imagen, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Imagen, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private EstudianteP Estudiantes;
private TrabajadorP Trabajadores;
private WebCam WebCam;

    public void setEstudiantes(EstudianteP Estudiantes) {
        this.Estudiantes = Estudiantes;
    }

    public void setTrabajadores(TrabajadorP Trabajadores) {
        this.Trabajadores = Trabajadores;
    }

    public void setWebCam(WebCam WebCam) {
        this.WebCam = WebCam;
    }
   

    private void ImagenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagenMouseClicked
 if(evt.getClickCount()==2){
              
     
        System.out.println("Ruta "+Ruta);
     if(Estudiantes!=null){
              Estudiantes.Foto(Ruta);
              Estudiantes.setFoto();
              this.WebCam.Cerrar();
     }
       if(Trabajadores != null ){
              Trabajadores.Foto(Ruta);
              Trabajadores.setFoto();
              this.WebCam.Cerrar();
     }
              
              this.dispose();
              
 }
               // TODO add your handling code here:
    }//GEN-LAST:event_ImagenMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Imagen;
    // End of variables declaration//GEN-END:variables
}
